version: "3.8"

services:
  mysql:
    build: ./database
    container_name: mysql
    networks:
      - my-net
    volumes:
      - my-vol:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: appdb

  api-gateway:
    build: ./api-gateway
    # container_name: api-gateway
    networks:
      - my-net
    depends_on:
      - mysql

  users-service:
    build: ./user-service
    # container_name: users-service
    networks:
      - my-net
    depends_on:
      - mysql

  products-service:
    build: ./product-service
    # container_name: products-service
    networks:
      - my-net
    depends_on:
      - mysql

  orders-service:
    build: ./order-service
    # container_name: orders-service
    networks:
      - my-net
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    # container_name: frontend
    networks:
      - my-net

  nginx:
    build: ./nginx
    # container_name: nginx
    ports:
      - "80:80"
    networks:
      - my-net
    depends_on:
      - frontend
      - api-gateway

networks:
  my-net:
    driver: bridge

volumes:
  my-vol:
