version: "3.8"

services:
  mysql:
    build: ./database
    container_name: mysql
    networks:
      - my-net
    volumes:
      - my-vol:/var/lib/mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: appdb

  api-gateway:
    build: ./api-gateway
    # container_name: api-gateway
    networks:
      - my-net
    depends_on:
      - mysql

  users-service:
    build: ./user-service
    # container_name: users-service
    networks:
      - my-net
    depends_on:
      - mysql

  products-service:
    build: ./product-service
    # container_name: products-service
    networks:
      - my-net
    depends_on:
      - mysql

  orders-service:
    build: ./order-service
    # container_name: orders-service
    networks:
      - my-net
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    # container_name: frontend
    networks:
      - my-net

  nginx:
    build: ./nginx
    # container_name: nginx
    ports:
      - "80:80"
    networks:
      - my-net
    depends_on:
      - frontend
      - api-gateway

networks:
  my-net:
    driver: bridge

volumes:
  my-vol:


------------------------

version: "3.8"

services:
  mysql:
    image: microservices-app/mysql:latest
    networks:
      - my-net
    volumes:
      - my-vol:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  users-service:
    image: microservices-app/users-service:latest
    networks:
      - my-net
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  products-service:
    image: microservices-app/products-service:latest
    networks:
      - my-net
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  orders-service:
    image: microservices-app/orders-service:latest
    networks:
      - my-net
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-gateway:
    image: microservices-app/api-gateway:latest
    networks:
      - my-net
    depends_on:
      - users-service
      - products-service
      - orders-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: microservices-app/frontend:latest
    networks:
      - my-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: microservices-app/nginx:latest
    ports:
      - "80:80"
    networks:
      - my-net
    depends_on:
      - frontend
      - api-gateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  my-net:
    driver: overlay

volumes:
  my-vol:
    driver: local

