version: "3.8"

services:
  db:
    build: ./database
    networks:
      - my-net
    volumes:
      - db-vol:/var/lib/postgresql/data

  be:
    build: ./backend
    networks:
      - my-net
    env_file: ./backend/.env
    
    depends_on:
      - db

  fe:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - my-net

networks:
  my-net:
    driver: bridge

volumes:
  db-vol:
