version: "3.8"

services:
  db:
    build: ./database
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - my-net

  be:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL","curl -I http://localhost:3000"]
    
    networks:
      - my-net

  fe:
    build: ./frontend
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL","curl -I http://localhost"]
    networks:
      - my-net

networks:
  my-net:
    driver: bridge

volumes:
  db-vol:
